services:
  user-service:
    container_name: user-service
    image: gaeun0811/user-service:${MUNGTIQUE_VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - USER_DB_URL=${USER_DB_URL}
      - PG_ID=${PG_ID}
      - PG_PW=${PG_PW}
      - KAFKA_URI=${KAFKA_URI}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - REDIS_IP=${REDIS_IP}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_SERVER_URL=${ZIPKIN_SERVER_URL}
      - ACCESS_EXPIRATION_TIME=${ACCESS_EXPIRATION_TIME}
      - REFRESH_EXPIRATION_TIME=${REFRESH_EXPIRATION_TIME}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - NAVER_AUTHORIZATION_URI=${NAVER_AUTHORIZATION_URI}
      - NAVER_TOKEN_URI=${NAVER_TOKEN_URI}
      - NAVER_USER_INFO_URI=${NAVER_USER_INFO_URI}
      - KAKAO_AUTHORIZATION_URI=${KAKAO_AUTHORIZATION_URI}
      - KAKAO_TOKEN_URI=${KAKAO_TOKEN_URI}
      - KAKAO_USER_INFO_URI=${KAKAO_USER_INFO_URI}
    ports:
      - "8082:8080"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/user/logs:/logs
    depends_on:
      - user-db
    networks:
      - mungtique

  user-db:
    image: postgres:latest
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ID}
      POSTGRES_PASSWORD: ${PG_PW}
    ports:
      - "54322:5432"
    volumes:
#      - ${HOST_OPERATION_DIR_PATH}/user/sql-init:/docker-entrypoint-initdb.d
#      - ${HOST_OPERATION_DIR_PATH}/user/db:/var/lib/postgresql/data
      - user-db-init:/docker-entrypoint-initdb.d
      - user-db-data:/var/lib/postgresql/data
    networks:
      - mungtique

volumes:
  user-db-data:
  user-db-init:

networks:
  mungtique:
    driver: bridge
    external: true