server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # 동기화 위해 promtail이 읽은 마지막 로그 정보 저장

clients:
  - url: http://loki:3100/loki/api/v1/push # loki 서버 주소 (다른 서버 Loki로 전송 가능)

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - loki
        labels:
          job: watcher-log
          __path__: /var/logs/*log
