version: '3.8'

services:
  care-service:
    container_name: care-service
    image: mungtique/care:${MUNGTIQUE_VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CARE_DB_URL=${CARE_DB_URL}
      - PG_ID=${PG_ID}
      - PG_PW=${PG_PW}
#      - KAFKA_URI=${KAFKA_URI}
#      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
#      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

    ports:
      - "8083:8080"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/care/logs:/logs
    depends_on:
      care-db:
        condition: service_healthy
    networks:
      - mungtique

  care-db:
    image: postgres:latest
    container_name: care-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ID}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: care
    ports:
      - "54324:5432"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/care/sql-init:/docker-entrypoint-initdb.d
      - ${HOST_OPERATION_DIR_PATH}/mount/care/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mungtique

networks:
  mungtique:
    driver: bridge
    external: true