version: "3.7"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana-volume:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - mung-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - ./prometheus/prometheus-volume:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--web.enable-lifecycle" # 재시작없이 설정파일 reload 할 수 있게 함
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    networks:
      - mung-network

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always
    networks:
      - mung-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: mungtique
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mungmung
      TZ: Asia/Seoul
    volumes:
      - /postgresql/data:/var/lib/postgresql/data
    networks:
      - mung-network

  pg_exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    container_name: pg_exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://mungtique:1234@postgres:5432/mungmung?sslmode=disable
    networks:
      - mung-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - mung-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../service/logs:/var/logs
      - ./loki/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - mung-network

networks:
  mung-network:
    driver: bridge
