version: "3.7"
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - mungtique

    zookeeper-1:
        image: bitnami/zookeeper:latest
        container_name: zookeeper-1
        user: "0:0"
        ports:
            - "2181:2181"
        volumes:
            - ${HOST_OPERATION_DIR_PATH}/zoo-1/data:/bitnami/zookeeper
            - ${HOST_OPERATION_DIR_PATH}/zoo-1/datalog:/opt/bitnami/zookeeper/logs/
            - ${HOST_OPERATION_DIR_PATH}/zoo-1/config/:/opt/bitnami/zookeeper/conf/
        environment:
            - ZOO_SERVER_ID=1
            - ALLOW_ANONYMOUS_LOGIN=yes
            - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888

    zookeeper-2:
        image: bitnami/zookeeper:latest
        container_name: zookeeper-2
        user: "0:0"
        ports:
            - "2182:2181"
        volumes:
            - ${HOST_OPERATION_DIR_PATH}/zoo-2/data:/bitnami/zookeeper
            - ${HOST_OPERATION_DIR_PATH}/zoo-2/datalog:/opt/bitnami/zookeeper/logs/
            - ${HOST_OPERATION_DIR_PATH}/zoo-2/config/:/opt/bitnami/zookeeper/conf/
        environment:
            - ZOO_SERVER_ID=2
            - ALLOW_ANONYMOUS_LOGIN=yes
            - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888

    zookeeper-3:
        image: bitnami/zookeeper:latest
        container_name: zookeeper-3
        user: "0:0"
        ports:
            - "2183:2181"
        volumes:
            - ${HOST_OPERATION_DIR_PATH}/zoo-3/data:/bitnami/zookeeper
            - ${HOST_OPERATION_DIR_PATH}/zoo-3/datalog:/opt/bitnami/zookeeper/logs/
            - ${HOST_OPERATION_DIR_PATH}/zoo-3/config/:/opt/bitnami/zookeeper/conf/
        environment:
            - ZOO_SERVER_ID=3
            - ALLOW_ANONYMOUS_LOGIN=yes
            - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888

    kafka-1:
        image: bitnami/kafka:latest
        container_name: kafka-1
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://${PUBLIC_IP}:29092
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
        ports:
            - "9092:9092"
            - "29092:29092"
        volumes:
            - ${HOST_OPERATION_DIR_PATH}/kafka-1/bitnami/kafka:/bitnami/kafka
            - ${HOST_OPERATION_DIR_PATH}/kafka-1/logs:/bitnami/kafka/data
            - ./shell/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3

    kafka-2:
        image: bitnami/kafka:latest
        container_name: kafka-2
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_BROKER_ID=2
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,PLAINTEXT_HOST://:29093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9093,PLAINTEXT_HOST://${PUBLIC_IP}:29093
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
        ports:
            - "9093:9093"
            - "29093:29093"
        volumes:
            - ${HOST_OPERATION_DIR_PATH}/kafka-2/bitnami/kafka:/bitnami/kafka
            - ${HOST_OPERATION_DIR_PATH}/kafka-2/logs:/bitnami/kafka/data
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
    kafka-3:
        image: bitnami/kafka:latest
        container_name: kafka-3
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_BROKER_ID=3
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,PLAINTEXT_HOST://:29094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9094,PLAINTEXT_HOST://${PUBLIC_IP}:29094
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
        ports:
            - "9094:9094"
            - "29094:29094"
        volumes:
            - ${HOST_OPERATION_DIR_PATH}/kafka-3/bitnami/kafka:/bitnami/kafka
            - ${HOST_OPERATION_DIR_PATH}/kafka-3/logs:/bitnami/kafka/data
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3

    kafka-ui:
        image: provectuslabs/kafka-ui
        container_name: kafka-ui
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
        ports:
            - "8989:8080"
        restart: always
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9093,kafka-3:9094
            # - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181

networks:
    mungtique:
        driver: bridge
        external: true
