global:
  scrape_interval: 15s # 데이터 가져오는 빈도
  scrape_timeout: 15s # 데이터 가져오는 작업이 완료되길 기다리는 시간
  query_log_file: saved.log

scrape_configs: # 스크랩할 대상
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "pg_exporter"
    static_configs:
      - targets: ["pg_exporter:9187"]

  - job_name: "user-service"
    metrics_path: "/user-service/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "mungshop-service"
    metrics_path: "/mungshop-service/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "dog-service"
    metrics_path: "/dog-service/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "reservation-service"
    metrics_path: "/reservation-service/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "payment-service"
    metrics_path: "/payment-service/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8000"]
