global:
  scrape_interval: 15s # 데이터 가져오는 빈도
  scrape_timeout: 15s # 데이터 가져오는 작업이 완료되길 기다리는 시간
  query_log_file: saved.log

scrape_configs: # 스크랩할 대상
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "pg_exporter"
    static_configs:
      - targets: ["pg_exporter:9187"]
