version: '3.8'

services:
  mungshop-service:
    container_name: mungshop-service
    image: mungtique/mungshop:${MUNGTIQUE_VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - mungshop_DB_URL=${mungshop_DB_URL}
      - PG_ID=${PG_ID}
      - PG_PW=${PG_PW}
      - KAFKA_URI=${KAFKA_URI}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

    ports:
      - "8083:8080"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/mungshop/logs:/logs
    depends_on:
      mungshop-db:
        condition: service_healthy
    networks:
      - mungtique

  mungshop-db:
    image: postgres:latest
    container_name: mungshop-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ID}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: mungshop
    ports:
      - "54324:5432"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/mungshop/sql-init:/docker-entrypoint-initdb.d
      - ${HOST_OPERATION_DIR_PATH}/mount/mungshop/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mungtique

networks:
  mungtique:
    driver: bridge
    external: true