services:
  mungshop-service:
    container_name: mungshop-service
    image: gaeun0811/mungshop-service:${MUNGTIQUE_VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MUNGSHOP_DB_URL=${MUNGSHOP_DB_URL}
      - PG_ID=${PG_ID}
      - PG_PW=${PG_PW}
      - KAFKA_URI=${KAFKA_URI}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - REDIS_IP=${REDIS_IP}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_SERVER_URL=${ZIPKIN_SERVER_URL}
    ports:
      - "8084:8080"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/mungshop/logs:/logs
    depends_on:
      - mungshop-db
    networks:
      - mungtique

  mungshop-db:
    image: postgres:latest
    container_name: mungshop-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ID}
      POSTGRES_PASSWORD: ${PG_PW}
    ports:
      - "54324:5432"
    volumes:
#      - ${HOST_OPERATION_DIR_PATH}/mungshop/sql-init:/docker-entrypoint-initdb.d
#      - ${HOST_OPERATION_DIR_PATH}/mount/mungshop/db:/var/lib/postgresql/data
      - mungshop-db-init:/docker-entrypoint-initdb.d
      - mungshop-db-data:/var/lib/postgresql/data
    networks:
      - mungtique

volumes:
  mungshop-db-data:
  mungshop-db-init:

networks:
  mungtique:
    driver: bridge
    external: true