logging:
  config: classpath:log4j2.yml

cors:
  allowed-origins: http://localhost:5173

spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://user-db:5432/mungtique?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    # TODO : secretKey를 알고리즘 사용해서 생성하기
    secret: sdjklfjdslkfieworfjjsdfxcnjjksdrhiwejhreijdlksauewrhkljsckljsdlfkjweolijriljfkldsj
    access-expiration: 600000 # 10분
    refresh-expiration: 86400000 # 24시간

  mail:
    host: smtp.gmail.com
    port: 587
    username: boradory353@gmail.com
    password: xeku dkfj cttb vubp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  # registration
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: zKjpwytYuGP3NHWSs8HL
            client-secret: NNSFAjfzQa
            redirect-uri: http://localhost:8082/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

          kakao:
            client-name: kakao
            client-id: 2d8f61562f1abc51544dad9a92b0040b
            client-secret: Z3S4oLyy78WLW6D6SXqPRhpRbhSC9P6d
            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

