server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/payment-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/v1/reservation-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/reservation-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: dog-service
          uri: lb://DOG-SERVICE
          predicates:
            - Path=/api/v1/dog-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/dog-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: mungshop-service
          uri: lb://MUNGSHOP-SERVICE
          predicates:
            - Path=/api/v1/mungshop-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/mungshop-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/api/v1/user-service/(?<segment>.*), /login # login은 security에서 자동 생성

        - id: user-service-logout
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /${segment} # logout은 security에서 자동 생성

        - id: user-service-reissue
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/reissue
            - Method=POST
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /${segment}

        - id: user-service-join
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-mail-check
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/mail-check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-mail-send
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/mail-send
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: user-service-oauth2-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/oauth2/authorization/**

        - id: user-service-oauth2-logout
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/oauth2/logout
            - Method=POST
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-oauth2
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/oauth2/**
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        # actuator
        - id: user-service-actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: mungshop-service-actuator
          uri: lb://MUNGSHOP-SERVICE
          predicates:
            - Path=/mungshop-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/mungshop-service/(?<segment>.*), /${segment}

        - id: dog-service-actuator
          uri: lb://DOG-SERVICE
          predicates:
            - Path=/dog-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/dog-service/(?<segment>.*), /${segment}

        - id: reservation-service-actuator
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation-service/(?<segment>.*), /${segment}

        - id: payment-service-actuator
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment-service/(?<segment>.*), /${segment}

  jwt:
    secret: ${TOKEN_SECRET}

eureka:
  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
  security:
    enabled: false