server:
  port: 8000
  forward-headers-strategy: framework

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://payment-service:8086
          predicates:
            - Path=/api/v1/payment-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/payment-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: reservation-service
          uri: http://reservation-service:8085
          predicates:
            - Path=/api/v1/reservation-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/reservation-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: dog-service
          uri: http://dog-service:8083
          predicates:
            - Path=/api/v1/dog-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/dog-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: mungshop-service
          uri: http://mungshop-service:8084
          predicates:
            - Path=/api/v1/mungshop-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/mungshop-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-login
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie # 쿠키 삭제 후 실행
            - RewritePath=/api/v1/user-service/(?<segment>.*), /login # login은 security에서 자동 생성

        - id: user-service-logout
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /${segment} # logout은 security에서 자동 생성

        - id: user-service-reissue
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/reissue
            - Method=POST
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /${segment}

        - id: user-service-join
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-mail-check
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/mail-check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-mail-send
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/mail-send
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}
            - AuthorizationHeaderFilter

        - id: user-service-oauth2-login
          uri: http://user-service:8082
          predicates:
            - Path=/oauth2/authorization/**

        - id: user-service-oauth2-logout
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/oauth2/logout
            - Method=POST
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        - id: user-service-oauth2
          uri: http://user-service:8082
          predicates:
            - Path=/api/v1/user-service/oauth2/**
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /api/v1/${segment}

        # actuator
        - id: user-service-actuator
          uri: http://user-service:8082
          predicates:
            - Path=/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: mungshop-service-actuator
          uri: http://mungshop-service:8084
          predicates:
            - Path=/mungshop-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/mungshop-service/(?<segment>.*), /${segment}

        - id: dog-service-actuator
          uri: http://dog-service:8083
          predicates:
            - Path=/dog-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/dog-service/(?<segment>.*), /${segment}

        - id: reservation-service-actuator
          uri: http://reservation-service:8085
          predicates:
            - Path=/reservation-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/reservation-service/(?<segment>.*), /${segment}

        - id: payment-service-actuator
          uri: http://payment-service:8086
          predicates:
            - Path=/payment-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment-service/(?<segment>.*), /${segment}

  jwt:
    secret: ${TOKEN_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

eureka:
  client:
    enabled: false