apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-configmap
data:
  SPRING_PROFILES_ACTIVE: "k8s-prod"
  KAFKA_URI: "192.168.49.2:29092,192.168.49.2:29093,192.168.49.2:29094"
  KAFKA_GROUP_ID: "mungtique-service"
  REDIS_IP: "192.168.49.2"
  REDIS_PORT: "6379"
  ZIPKIN_SERVER_URL: "http://192.168.49.2:9411/api/v2/spans"
  ACCESS_EXPIRATION_TIME: "600000"
  REFRESH_EXPIRATION_TIME: "86400000"

  USER_DB_URL: "user-db"
  DOG_DB_URL: "dog-db"
  MUNGSHOP_DB_URL: "mungshop-db"
  RESERVATION_DB_URL: "reservation-db"
  PAYMENT_DB_URL: "payment-db"

  MUNGSHOP_SERVICE_URL: "http://mungshop-service:8084"


#  gateway_ip: "192.168.49.2"
#  order-service-url: "http://order-service:10000"
#  bootstrap-servers: "192.168.49.2:9092"