apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-deploy
spec:
  selector:
    matchLabels:
      app: dog-service
  replicas: 1
  template:
    metadata:
      labels:
        app: dog-service
    spec:
      containers:
        - name: dog-service
          image: gaeun0811/dog-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: DOG_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: DOG_DB_URL
            - name: KAFKA_URI
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: KAFKA_URI
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: KAFKA_GROUP_ID
            - name: REDIS_IP
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: REDIS_IP
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: REDIS_PORT
            - name: ZIPKIN_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: ZIPKIN_SERVER_URL
            # 🔒 Secret 값 적용
            - name: PG_ID
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_ID
            - name: PG_PW
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_PW
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: AWS_SECRET_KEY
            - name: FILE_SERVER_BUCKET
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: FILE_SERVER_BUCKET

          volumeMounts:
            - name: logs
              mountPath: /logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: dog-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dog-service
spec:
  type: NodePort
  selector:
    app: dog-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-db
  template:
    metadata:
      labels:
        app: dog-db
    spec:
      containers:
        - name: dog-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_PW
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-init
          persistentVolumeClaim:
            claimName: dog-db-init-pvc
        - name: db-data
          persistentVolumeClaim:
            claimName: dog-db-data-pvc
---
apiVersion: v1

kind: Service
metadata:
  name: dog-db
spec:
  type: NodePort
  selector:
    app: dog-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31003
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dog-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dog-db-init-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dog-db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi