apiVersion: apps/v1
kind: Deployment
metadata:
  name: mungshop-deploy
spec:
  selector:
    matchLabels:
      app: mungshop-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mungshop-service
    spec:
      containers:
        - name: mungshop-service
          image: gaeun0811/mungshop-service:${MUNGTIQUE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: MUNGSHOP_DB_URL
            - name: KAFKA_URI
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: KAFKA_URI
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: KAFKA_GROUP_ID
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: EUREKA_SERVER_URL
            - name: REDIS_IP
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: REDIS_IP
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: REDIS_PORT
            - name: ZIPKIN_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-configmap
                  key: ZIPKIN_SERVER_URL
            # 🔒 Secret 값 적용
            - name: PG_ID
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_ID
            - name: PG_PW
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_PW
          volumeMounts:
            - name: logs
              mountPath: /logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: mungshop-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mungshop-service
spec:
  type: NodePort
  selector:
    app: mungshop-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mungshop-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mungshop-db
  template:
    metadata:
      labels:
        app: mungshop-db
    spec:
      containers:
        - name: mungshop-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_ID
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: PG_PW
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-init
          persistentVolumeClaim:
            claimName: mungshop-db-init-pvc
        - name: db-data
          persistentVolumeClaim:
            claimName: mungshop-db-data-pvc
---
apiVersion: v1

kind: Service
metadata:
  name: mungshop-db
spec:
  type: NodePort
  selector:
    app: mungshop-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31004
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mungshop-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mungshop-db-init-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mungshop-db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi