services:
  payment-service:
    container_name: payment-service
    image: gaeun0811/payment-service:${MUNGTIQUE_VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DB_URL=${PAYMENT_DB_URL}
      - PG_ID=${PG_ID}
      - PG_PW=${PG_PW}
      - KAFKA_URI=${KAFKA_URI}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
      - ZIPKIN_SERVER_URL=${ZIPKIN_SERVER_URL}
    ports:
      - "8086:8080"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/payment/logs:/logs
    depends_on:
      - payment-db
    networks:
      - mungtique

  payment-db:
    image: postgres:latest
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ID}
      POSTGRES_PASSWORD: ${PG_PW}
    ports:
      - "54326:5432"
    volumes:
#      - ${HOST_OPERATION_DIR_PATH}/payment/sql-init:/docker-entrypoint-initdb.d
#      - ${HOST_OPERATION_DIR_PATH}/mount/payment/db:/var/lib/postgresql/data
      - payment-db-init:/docker-entrypoint-initdb.d
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - mungtique

volumes:
  payment-db-data:
  payment-db-init:

networks:
  mungtique:
    driver: bridge
    external: true