version: '3.8'

services:
  payment-service:
    container_name: payment-service
    image: mungtique/payment:${MUNGTIQUE_VERSION}
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - PAYMENT_DB_URL=${PAYMENT_DB_URL}
      - PG_ID=${PG_ID}
      - PG_PW=${PG_PW}
      - KAFKA_URI=${KAFKA_URI}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

    ports:
      - "8083:8080"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/payment/logs:/logs
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - mungtique

  payment-db:
    image: postgres:latest
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_ID}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: payment
    ports:
      - "54324:5432"
    volumes:
      - ${HOST_OPERATION_DIR_PATH}/payment/sql-init:/docker-entrypoint-initdb.d
      - ${HOST_OPERATION_DIR_PATH}/mount/payment/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mungtique

networks:
  mungtique:
    driver: bridge
    external: true