spring:
  application:
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PAYMENT_DB_URL}:5432/postgres
    username: ${PG_ID}
    password: ${PG_PW}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: ${KAFKA_URI}
    consumer:
      group-id: ${KAFKA_GROUP_ID}

eureka:
  instance:
#    instance-id: ${spring.cloud.client.hostname}:${server.port}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER_URL}

  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
